### PR TITLE
feat/fix: fix #13 & add edge manipulation and deletion

### LINKED ISSUE #13: bug: shouldn't allow connecting multiple parents to the same node
was playing around with connecting random things and got this
which does nothing (I think?)

image

### PR DESCRIPTION
**Pull request by Christofon**
Fixed #13

I am not sure the edge manipulation via mouse drag is something that should be possible but I thought it makes sense.

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -163,14 +164,40 @@ function App() {
...
+  }, [nodes, edges]);
+
+  const onEdgeUpdateEnd = useCallback((_: unknown, edge: Edge<any>) => {
+    if (!edgeUpdateSuccessful.current) {
+      setEdges((edges) => edges.filter((e) => e.id !== edge.id));
+    }
+
+    edgeUpdateSuccessful.current = true;
+  }, []);
+
```
Comment (transmissions11) [inline src/components/App.tsx:189]: wait sorry why do we need these extra callbacks? returning in `onConnect` accomplishes what we need no?

otherwise lgtm

Comment (transmissions11) [reply src/components/App.tsx:189]: oh i see this is to add edge manipulation?

Comment (Christofon) [reply src/components/App.tsx:189]: > oh i see this is to add edge manipulation?

yes, not sure this is something you want but thought it makes sense now that there is only one parent enforced.

Comment (transmissions11) [reply src/components/App.tsx:189]: yeah this looks great actually— nice job. in the future would prefer if these were two PRs as this jumbles a bit of complexity but no worries this time

File: src/components/App.tsx [hunk 2]
```diff
@@ -163,14 +164,40 @@ function App() {
...
+  const edgeUpdateSuccessful = useRef(true);
+
+  const onEdgeUpdateStart = useCallback(() => {
+    edgeUpdateSuccessful.current = false;
+  }, []);
+
+  const onEdgeUpdate = useCallback((oldEdge: Edge<any>, newConnection: Connection) => {
+    if (getFluxNodeParent(nodes, edges, newConnection.target!) !== undefined) {
+      return;
+    }
```
Comment (transmissions11) [inline src/components/App.tsx:176]: we also need a check for 

```
 isFluxNodeInLineage(nodes, edges, {
        nodeToCheck: connection.target!,
        nodeToGetLineageOf: connection.source!,
      })
```

to prevent recursive loops

File: src/components/App.tsx (hunk 1 above)
Comment (Christofon) [reply src/components/App.tsx:189]: Makes sense, will remember that :)

File: src/components/App.tsx [hunk 3]
```diff
@@ -163,14 +164,40 @@ function App() {
...
+
+  const onEdgeUpdateEnd = useCallback((_: unknown, edge: Edge<any>) => {
+    if (!edgeUpdateSuccessful.current) {
+      setEdges((edges) => edges.filter((e) => e.id !== edge.id));
+    }
+
+    edgeUpdateSuccessful.current = true;
+  }, []);
+
   const onConnect = (connection: Edge<any> | Connection) => {
```
Comment (transmissions11) [inline src/components/App.tsx:190]: also while we're at it, let's useCallback this?

Comment (transmissions11) [reply src/components/App.tsx:190]: ah well wait we depend on `edges` AND `nodes` here... nvm too much complexity for this PR

can maybe do in a followup https://github.com/transmissions11/flux/issues/31

File: src/components/App.tsx (hunk 2 above)
Comment (transmissions11) [reply src/components/App.tsx:176]: could maybe extract these two checks into a joint function in `fluxNodes` since we're now using them twice

Comment (Christofon) [reply src/components/App.tsx]: done

**Comment by transmissions11** [comment]
lgtm, thank you so much @Christofon!
